	<section id="register-area" class="">
		<div class="register-page">
			<section id="introducing" class="register-introduce bg-primary">
				<div class="introducing">
					<h1 class="lobster">Tạo tài khoản Mỹ Phố</h1>
					<div class="description font-italic obster">
						<p>Trước khi tạo tài khoản, bạn cần biết những điều sau đây:</p>
						<ul>
							<li>Chúng tôi không liên kết với các mạng xã hội khác vì đây là một website độc lập chỉ dành riêng cho nhũng người ủng hộ LGBTQI+</li>
							<li>Các tài khoản trên Website sẽ hoạt động độc lập, chúng tôi không ủng hộ việc sở hữu nhiều tài khoản. Do đó, hãy nhập đầy đủ thông tin bảo mật</li>
							<li>Chúng tôi sẽ lưu mọi lịch sử hoạt động trên tài khoản của bạn</li>
							<li>Không khuyến khích chia sẽ những thông tin nhạy cảm, bạo lực, vượt mức cho phép vì một cộng đồng văn minh và lành mạnh (Tui thừa biết mấy thím không còn tiết tháo, nhưng nhớ kiềm chế lại =)))</li>
							<li>Không spam, không phá hoại, tạo tài khoản ảo. Chúng tôi luôn kiểm tra và rà xoát liên tục những hành vi cố ý phá hoại, gây rối trên website</li>
						</ul>
					</div>
					<div class="copyright mt-5">
						<small class="font-italic">- From Admin</small>
					</div>
				</div>
			</section>
			<main class="register-form">
				<center>
					<h2 class="lobster"> Tạo tài khoản </h2>
				</center>

				<form class="form-horizontal" action="/register" method="post">
					<?php if(isset($this->error)): ?>
					<div class="form-group">
						<div class="alert alert-danger">
							<?php foreach($this->error as $m => $t): ?>
							<div class="mb-1">- <?= $t ?></div>
							<?php endforeach; ?>
						</div>
					</div>
					<?php endif; ?>
					<div class="form-group">
						<label for="email" class="lobster">Email</label>
						<div class="input-group">
							<input type="text" class="form-control" name="email" placeholder="Địa chỉ email của bạn" />
						</div>
					</div>
					<div class="form-group">
						<label for="account" class="lobster">Tên tài khoản</label>
						<div class="input-group">
							<input type="text" class="form-control" name="account" placeholder="Ví dụ congchua01" />
						</div>
					</div>
					<div class="form-group">
						<label for="password" class="lobster">Mật khẩu</label>
						<div class="input-group">
							<input type="password" class="form-control" name="password" placeholder="Nhập mật khẩu" />
						</div>
					</div>
					<div class="form-group">
						<label for="repassword" class="lobster">Nhập lại mật khẩu</label>
						<div class="input-group">
							<input type="password" class="form-control" name="repassword" placeholder="Nhập lại mật khẩu" />
						</div>
					</div>
					<div class="form-group">
						<label for="name" class="lobster">Bút danh</label>
						<div class="input-group">
							<input type="text" class="form-control" name="name" placeholder="Tên bạn sẽ dùng trên website" />
						</div>
					</div>
					<div class="form-group">
						<label for="gender" class="lobster">Thể loại</label>
						<div class="input-group">
							<select class="custom-select" name="gender">
								<option value="0">Hủ Nam</option>
								<option value="1">Hủ Nữ</option>
								<option value="2">Công</option>
								<option value="3">Thụ</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<lable for="captcha" class="lobster">Mã xác nhận</lable>
						<div class="container-fluid px-0">
							<div class="d-flex">
								<div class="flex-fill pr-2">
									<img src="/captcha" width="140px" />
								</div>
								<div class="flex-fill">
									<input type="text" class="form-control" name="captcha" placeholder="Nhập mã bên trái">
								</div>
							</div>
						</div>	
					</div>
					<div class="form-group">
						<label for="ts"><i class="fa fa-check-circle text-primary"></i> <small class="font-italic">Bạn đã đồng ý với quy định của chúng tôi nếu bạn vẫn tiếp tục tạo tài khoản</small></label>
					</div>
					<input type="hidden" name="<?= $this->token->get('name'); ?>" value="<?= $this->token->get('value'); ?>">
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-block">Tạo tài khoản</button>
					</div>

					<section id="forgot-password" class="mt-4 text-center">
						Đã có tài khoản?
					</section>

					<section id="register" class="mt-3">
						<a href="/register" class="btn btn-light btn-block">Đăng nhập</a>
					</section>
				</form>

				<div class="copyright mt-5 text-center">
					<small class="font-italic">Copright &copy; 2020 mPho - Mỹ Phố</small>
				</div>
			</main>
		</div>
	</section>