	<section id="login-area" class="">
		<div class="login-page">
			<section id="introducing" class="login-introduce bg-primary">
				<div class="introducing">
					<h4 class="lobster">Chào mừng bạn đến với</h4>
					<div class="intro-brand lobster">Mỹ Phố</div>
					<h4 class="lobster">Website chỉ dành cho hủ</h4>
					<div class="description font-italic obster">
						~~ Đây là website chỉ dành riêng cho hủ, nơi mà chúng hủ có thể thỏa thích rụng rời tiết tháo, rụng rời tam quan và đánh mất liêm sỉ. không chỉ thế, chúng tôi còn tích hợp rất nhiều chức năng khác nhau (từ kinh nghiệm của admin là một con hủ lâu năm) để thỏa mãn được yêu cầu của các đồng râm. Còn chần chờ làm chi nữa? Vào quẩy thôi ~~
					</div>
					<div class="copyright mt-5">
						<small class="font-italic">- From Admin</small>
					</div>
				</div>
			</section>
			<main class="login-form">
				<center>
					<h2 class="lobster"> Đăng nhập </h2>
				</center>

				<form class="form-horizontal" action="" method="post">

					<?php if(isset($_GET['a']) OR isset($this->error)): ?>
					<div class="form-group">
						<div class="alert alert-<?= isset($this->error) ? 'danger' : 'success'; ?>">
							<?= isset($this->error) ? $this->error : 'Bạn đã tạo tài khoản thành công'; ?>
						</div>
					</div>
					<?php endif ?>
					<div class="form-group">
						<label for="user" class="lobster">Tài khoản</label>
						<div class="input-group">
							<input type="text" class="form-control" name="user" placeholder="Email hoặc tên tài khoản" />
						</div>
					</div>
					<div class="form-group">
						<label for="password" class="lobster">Mật khẩu</label>
						<div class="input-group">
							<input type="password" class="form-control" name="password" placeholder="Nhập mật khẩu" />
						</div>
					</div>
					<div class="form-group">
						<div class="custom-control custom-checkbox">
							<input type="checkbox" class="custom-control-input" id="remember" name="remember">
							<label class="custom-control-label" for="remember"><small class="font-italic">Lưu tài khoản cho các lần đăng nhập tiếp theo</small></label>
						</div>
					</div>
					<input type="hidden" name="<?= $this->token->get('name'); ?>" value="<?= $this->token->get('value'); ?>" />
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-block">Đăng nhập</button>
					</div>

					<section id="forgot-password" class="mt-4 text-center">
						<a href="">Quên mật khẩu</a>
					</section>

					<section id="register" class="mt-3">
						<a href="/register" class="btn btn-light btn-block">Chưa có tài khoản</a>
					</section>
				</form>

				<div class="copyright mt-5 text-center">
					<small class="font-italic">Copright &copy; 2020 mPho - Mỹ Phố</small>
				</div>
			</main>
		</div>
	</section>